name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      
      - name: delete package
        run: |
          rm -rf node_modules
          rm -f yarn.lock

      - name: Install dependencies       
        run: yarn install

      - name: generate all types
        run: yarn generate:types

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test