name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"

      - name: delete package
        run: |
          rm -rf node_modules
          rm -f yarn.lock

      - name: load env production
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" | tr -d '\r' > .env.production

      - name: Install dependencies, build and test app
        run: |
          yarn --exact
          yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      DIST: dist
      REGION: us-east-1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.REGION}}

      - name: Copy files to the production website via aws cli
        run: |
          aws s3 sync --delete ${{env.DIST}} s3://${{secrets.BUCKET}}

      - name: Create invalidation to clear cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{secrets.DIST_ID}} --paths "/*"
